spring.application.name=ExpenseTracker
spring.datasource.url=jdbc:h2:mem:test_payment
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
jwt.secret=your_super_secret_key_here